package br.edu.mackenzie.gerenciadornomes;

import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

// Import de Banco de Dados JDBC
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;

@SpringBootApplication
public class GerenciadorNomesApplication implements CommandLineRunner {

    public static void main(String[] args) {
        SpringApplication.run(GerenciadorNomesApplication.class, args);
    }

    @Override
    public void run(String... args) {

        // Conexao com banco de dados
        String url = "jdbc:h2:file:./data/banco_dados";
        String usuario = "admin";
        String senha = "admin";

        try (Connection connection =
                DriverManager.getConnection(url, usuario, senha);
            Statement statement = connection.createStatement()) {

            statement.execute("""
                CREATE TABLE IF NOT EXISTS analises (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                arquivo VARCHAR(500) NOT NULL,
                registros_validos INT NOT NULL,
                quantidade_falhas INT NOT NULL,
                tempo_medio_payments DOUBLE NOT NULL
                );
                """);
            
            analisadorArquivo(connection);
            exibirHistorico(connection);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
 private void salvarAnalise(
        Connection connection,
        String arquivo,
        int registrosValidos,
        int quantidadeFalhas,
        double tempoMedioPayments) throws Exception {

    String sql = """
        INSERT INTO analises
        (arquivo, registros_validos, quantidade_falhas, tempo_medio_payments)
        VALUES (?, ?, ?, ?)
        """;

    try (var statement = connection.prepareStatement(sql)) {

        statement.setString(1, arquivo);
        statement.setInt(2, registrosValidos);
        statement.setInt(3, quantidadeFalhas);
        statement.setDouble(4, tempoMedioPayments);

        statement.executeUpdate();
    }
}

    private void exibirHistorico(Connection connection) throws Exception {

    String sql = """
        SELECT id, arquivo, registros_validos,
               quantidade_falhas, tempo_medio_payments
        FROM analises
        ORDER BY id
        """;

    try (var statement = connection.createStatement();
         var resultSet = statement.executeQuery(sql)) {

        System.out.println("\n===== HISTÓRICO DE ANÁLISES =====");

        while (resultSet.next()) {

            System.out.println("ID: " + resultSet.getLong("id"));
            System.out.println("Arquivo: " + resultSet.getString("arquivo"));
            System.out.println("Registros válidos: "
                    + resultSet.getInt("registros_validos"));
            System.out.println("Quantidade de falhas: "
                    + resultSet.getInt("quantidade_falhas"));
            System.out.println("Tempo médio /api/v1/payments: "
                    + resultSet.getDouble("tempo_medio_payments"));
            System.out.println("--------------------------------");
        }
    }
}
private void analisadorArquivo(Connection connection){


}

}